version: '2'
services:
  mariadb:
    build: ./docker/db
    volumes:
      - 'nof_mariadb_data:/var/lib/mysql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_USER=root
      - MARIADB_DATABASE=notonlyfans
  app:
    build: ./docker/app
    depends_on:
      - mariadb
    ports:
      - '80:80'
    volumes:
      - './www:/app'
    
volumes:
  nof_mariadb_data:
    driver: local